// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCodeInstance(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ForceRemoveContainer(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function ListAllContainersJSON():Promise<Array<main.containerDetail>>;

export function ListImages():Promise<Array<main.imageDetail>>;

export function RemoveContainer(arg1:string,arg2:boolean):Promise<void>;

export function RemoveImages(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SelectFolder():Promise<string>;

export function StartContainer(arg1:string):Promise<string>;

export function StopContainer(arg1:string):Promise<string>;

export function URL(arg1:string):Promise<void>;
