// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCodeInstance(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCodeInstance'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateDB(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateDB'](arg1, arg2, arg3, arg4, arg5);
}

export function ForceRemoveContainer(arg1) {
  return window['go']['main']['App']['ForceRemoveContainer'](arg1);
}

export function GetCPUStats(arg1) {
  return window['go']['main']['App']['GetCPUStats'](arg1);
}

export function GetContainerMetrics(arg1) {
  return window['go']['main']['App']['GetContainerMetrics'](arg1);
}

export function GetImageLayerSize(arg1) {
  return window['go']['main']['App']['GetImageLayerSize'](arg1);
}

export function GetMemoryStats(arg1) {
  return window['go']['main']['App']['GetMemoryStats'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAllContainersJSON() {
  return window['go']['main']['App']['ListAllContainersJSON']();
}

export function ListImages() {
  return window['go']['main']['App']['ListImages']();
}

export function OpenPostgresTerminal(arg1, arg2) {
  return window['go']['main']['App']['OpenPostgresTerminal'](arg1, arg2);
}

export function RemoveContainer(arg1, arg2) {
  return window['go']['main']['App']['RemoveContainer'](arg1, arg2);
}

export function RemoveImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveImages'](arg1, arg2, arg3);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartContainer(arg1, arg2) {
  return window['go']['main']['App']['StartContainer'](arg1, arg2);
}

export function StopContainer(arg1) {
  return window['go']['main']['App']['StopContainer'](arg1);
}

export function URL(arg1) {
  return window['go']['main']['App']['URL'](arg1);
}
